export const commands = {
    rm: 'rm',
    rn: 'rn',
    mv: 'mv',
    cat: 'cat',
    cp: 'cp',
    add: 'add',
    ls: 'ls',
    up: 'up',
    cd: 'cd',
    os: 'os',
    hash: 'hash',
    compress: 'compress',
    decompress: 'decompress',
};
